---
name: IntPub — The Interplanetary Publishing Protocol
description: The Interplanetary Publishing Protocol (IntPub) is a tool researchers, academics, and scientists can use to self-publish their works on uncensorable & decentralized networks. 
author: The Daring LLC
url: "https://dar.i.ng/"
